packages:
  - 'demo'
  - 'demo-solid'

onlyBuiltDependencies:
  - '@rocicorp/zero-sqlite3'
  - esbuild
  - protobufjs

allowBuilds:
  '@rocicorp/zero-sqlite3': true
  esbuild: true
  protobufjs: true

minimumReleaseAgeExclude:
  - '@rocicorp/zero'
